name: Build Stonefish

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC

jobs:
  build:
      name: Build Stonefish
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            path: stonefish

        - name: Make build script executable
          working-directory: stonefish
          run: chmod +x scripts/build-stonefish.sh

        - name: Run build script
          working-directory: stonefish
          run: ./scripts/build-stonefish.sh
